name: Run tests

on: [push, pull_request]

jobs:
  build:
    name: Run tests
    timeout-minutes: 10
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            neovim_version: 'v0.5.1'
          - os: ubuntu-latest
            neovim_version: 'v0.6.1'
          - os: ubuntu-latest
            neovim_version: 'v0.7.2'
          - os: ubuntu-latest
            neovim_version: 'nightly'
          - os: windows-latest
            neovim_version: 'v0.7.2'
          - os: windows-latest
            neovim_version: 'nightly'
          - os: macos-latest
            neovim_version: 'nightly'
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - run: date +%F > todays-date
      - name: Restore cache for today's nightly.
        uses: actions/cache@v2
        with:
          path: _neovim
          key: ${{ runner.os }}-x64-${{ hashFiles('todays-date') }}
      - name: Setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim_version }}
      - name: Run tests
        run: make test
